duokan:
  cookie: ''
wps:
  uid: '123456'
cg:
  token: ''
  skey: ''
ssly:
  uid: 12487
everphoto:
  phone: ''
  password: ''
sxmd:
  account: ''
  password: ''
ucloud:
  token: ''
rrsp:
  rrtoken: ''
hykb:
  scookie: ''
  gid: ''
  invitecode: ''
du163:
  xsrf: ''
  X-Auth-Token: ''
w2pj:
  cookie: ''
xiang5:
  cookie: ''
notice:
  tgbot_token: ''
  serverj: ''
  coolpush: ''
jd:
  cookie: ''
jjwxc:
  cookie: ''
smzdm:
  cookie: ''
cg163:
  Authorization: ''
lkong:
  cookie: ''
pinggu:
  cookie: ''
nga:
  uid: ''
  accesstoken: ''
csdn:
  cookie: ''
mt:
  cookie: ''
  time: ''
sfacg:
  cookie: ''
maoer:
  cookie: ''
aihao:
  cookie: ''
hbooker:
  login_name: ''
  passwd: ''
acfun:
  phone: ''
  password: ''
diygm:
  cookie: ''